name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ./tests
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hamburger
        path: build
